### ISSUE TITLE
Improve validation messages

### ISSUE THREAD

**Issue by fredbi** [go-openapi/validate#44]
We should improve the quality of messages reported by the validation.
In particular, we should be able in one single validation pass, to report about most known errors.
Also, validate should more resilient to spec errors and avoid panicking as much as possible.

## Fix the following issues
A number of issues have already been posted about this.
This issue recaps the ones that might be short term improvements.

  - [x] Issue go-openapi/validate#16 - Cached compiled regexp
  - [x] Issue go-openapi/validate#12 - Multiple instances of messages
  - [x] Issue go-swagger/go-swagger#1307 - Multiple instances of messages (duplicate of go-openapi/validate#12)
  - [x] Issue go-swagger/go-swagger#1050 - Variant in path params (e.g. dot separated)
  - [x] Issue go-swagger/go-swagger#1243 - Explicit error for $ref within headers
  - [x] Issue go-swagger/go-swagger#161 - parameter items validation (a default value check)
  - [x] Issue go-swagger/go-swagger#859 - Richer message for unresolvable $ref
        (better than "object has no key").
  
## Add the following validation features
(not in other existing issues)
  - [x] Improve checks on garbled path params ({x/y} , ..)
  - [x] Check for path param uniqueness
  - [x] Check path params are declared as required
  - [x] Optional "continue on error" mode, to allow for checks to continue and sweep through all 
          detected errors.
  - [x] Replace regexp.MustCompile based on external output by simple compile and error management
  - [x] More unit testing, with stricter assertions on errors, warnings and their numbers
  - [x] Add check on multipleOf factor which must be positive

**Comment by fredbi** [comment]
This list should be solved with PR #42
